services:
  postgres:
    ports:
      - '127.0.0.1:5432:5432'
  migrate:
    environment:
      CAUSALITY_TOKEN_ENCRYPTION_KEY: ${CAUSALITY_TOKEN_ENCRYPTION_KEY:-dHR0dHR0dHR0dHR0dHR0dHR0dHR0dHR0dHR0dHR0dHQ=}
  api:
    environment:
      CAUSALITY_TOKEN_ENCRYPTION_KEY: ${CAUSALITY_TOKEN_ENCRYPTION_KEY:-dHR0dHR0dHR0dHR0dHR0dHR0dHR0dHR0dHR0dHR0dHQ=}
